
package base_de_donne;

import Application.BDD;
import Application.Parametre;
import Application.ResultSetTableModel;
import java.sql.*;
import javax.swing.JOptionPane;

public class Utilisateur extends javax.swing.JFrame {
ResultSet rs;
BDD db;
    public Utilisateur() {
        db= new BDD(new Parametre() .HOST_DB,new Parametre() .USERNAME_DB,new Parametre() .PASSWORD_DB,new Parametre() .IPHOST,new Parametre() .PORT);
        initComponents();
        table();
    }
    public void table(){
        String a [] = {"id", "id_user", "username", "password", "type"};
        rs = db.querySelect(a, "Utilisateur");
        table_user.setModel(new ResultSetTableModel(rs));
    }
    void Actualiser(){
        txt_id.setText("");
        txt_us.setText("");
        txt_pa.setText("");
        com_ty.setSelectedItem("type");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_user = new javax.swing.JTable();
        txtrech = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id = new javax.swing.JLabel();
        txt_rech = new javax.swing.JLabel();
        txt_us = new javax.swing.JLabel();
        txt_pa = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        comrech = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        com_ty = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Utilisateur");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(187, 5, 159, 44);

        table_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "id_user", "username", "password", "type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_user);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 540, 90);

        txtrech.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtrech.setText("Recherche");
        txtrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrechActionPerformed(evt);
            }
        });
        getContentPane().add(txtrech);
        txtrech.setBounds(250, 320, 140, 30);

        jToggleButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jToggleButton2.setText("Ajouter");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(20, 200, 105, 30);

        jToggleButton3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jToggleButton3.setText("Modifier");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3);
        jToggleButton3.setBounds(140, 200, 120, 30);

        jToggleButton4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jToggleButton4.setText("Supprimer");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton4);
        jToggleButton4.setBounds(270, 200, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 440, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Recherche par categorie:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 270, 210, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 360, 110, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 400, 100, 30);

        txt_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id.setText("jLabel6");
        getContentPane().add(txt_id);
        txt_id.setBounds(150, 320, 43, 17);

        txt_rech.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_rech.setText("jLabel6");
        getContentPane().add(txt_rech);
        txt_rech.setBounds(460, 320, 110, 30);

        txt_us.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_us.setText("jLabel6");
        getContentPane().add(txt_us);
        txt_us.setBounds(150, 360, 80, 30);

        txt_pa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_pa.setText("jLabel6");
        getContentPane().add(txt_pa);
        txt_pa.setBounds(140, 400, 80, 30);

        jToggleButton5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jToggleButton5.setText("Actualiser");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton5);
        jToggleButton5.setBounds(420, 200, 131, 30);

        comrech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id_user", "username", "password", "type" }));
        comrech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comrechMouseClicked(evt);
            }
        });
        comrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comrechActionPerformed(evt);
            }
        });
        getContentPane().add(comrech);
        comrech.setBounds(460, 270, 120, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("id_user");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 320, 60, 20);

        com_ty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pharmacien", "Directeur" }));
        com_ty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_tyActionPerformed(evt);
            }
        });
        getContentPane().add(com_ty);
        com_ty.setBounds(120, 440, 110, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
if (txt_id.getText().equals("") || txt_us.getText().equals("") ||
                txt_pa.getText().equals("") || com_ty.getSelectedItem().equals("type")) {
            JOptionPane.showMessageDialog(this, "SVP entrez les informations completes");
        } 
        else{
            String [] colon={"id_user", "username", "password", "type"};
            String[] inf = {txt_id.getText(), txt_us.getText(), txt_pa.getText(), com_ty.getSelectedItem().toString()};
            String id = String.valueOf(table_user.getValueAt(table_user.getSelectedRow(),0));
            System.out.println(db.queryUpdate("Utilisateur", colon, inf, "id'" + id + ";"));
            table();
            Actualiser();
            
        }

                     
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
String id = String.valueOf(table_user.getValueAt(table_user.getSelectedRow(),0)); 
if(JOptionPane.showConfirmDialog(this, "Etes-vous sur de vouloir supprimer", "Attention!!!", 
        JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION);
{
    db.queryDelete("Utilisateur", "id" + id);
} 
//else
        //return  ;
    //}
    table();
       
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void txtrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrechActionPerformed
        if (txtrech.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Entrez quelque chose SVP");
        }else {
            if(comrech.getSelectedItem().equals("id_user")){
                rs = db.querySelectAll("Utilisateur", "id_user LIKE ' %" + txtrech.getText() + "%'" );
                table_user.setModel(new ResultSetTableModel(rs));
            }else if (comrech.getSelectedItem().equals("username")){
                rs = db.querySelectAll("Utilisateur", "username LIKE ' %" + txtrech.getText() + "%'" );
                table_user.setModel(new ResultSetTableModel(rs));
            }else if (comrech.getSelectedItem().equals("password")){
                rs = db.querySelectAll("Utilisateur", "password LIKE ' %" + txtrech.getText() + "%'" );
                table_user.setModel(new ResultSetTableModel(rs));
            }else if (comrech.getSelectedItem().equals("type")){
                rs = db.querySelectAll("Utilisateur", "type LIKE ' %" + txtrech.getText() + "%'" );
                table_user.setModel(new ResultSetTableModel(rs));
            }
        }
    }//GEN-LAST:event_txtrechActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        Actualiser();
        table();
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void comrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comrechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comrechActionPerformed

    private void com_tyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_tyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_tyActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        if (txt_id.getText().equals("") || txt_us.getText().equals("") ||
                txt_pa.getText().equals("") || com_ty.getSelectedItem().equals("type")) {
            JOptionPane.showMessageDialog(this, "SVP entrez les informations completes");
        } 
        else{
            String [] colon={"id_user", "username", "password", "type"};
    String[] inf = {txt_id.getText(), txt_us.getText(), txt_pa.getText(), com_ty.getSelectedItem().toString()};
            System.out.println(db.queryInsert("Utilisateur", colon, inf));
            table();
            Actualiser();
            
        }

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void comrechMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comrechMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comrechMouseClicked

    private void table_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_userMouseClicked
    txt_id.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 1)));
    txt_us.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 2)));
    txt_pa.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 3)));
    com_ty.setSelectedItem(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 4)));  // TODO add your handling code here:
    }//GEN-LAST:event_table_userMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com_ty;
    private javax.swing.JComboBox<String> comrech;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JTable table_user;
    private javax.swing.JLabel txt_id;
    private javax.swing.JLabel txt_pa;
    private javax.swing.JLabel txt_rech;
    private javax.swing.JLabel txt_us;
    private javax.swing.JToggleButton txtrech;
    // End of variables declaration//GEN-END:variables
}
